title: Juan Miguel Villanueva
logo: https://github.com/jmvillan94/JuanMiguelVillanueva-Portfolio/blob/8ffc67d6c7f414d713c05c9eae19e0690aead62f/assets/Miguel%20Photo.jpg
description: text below image
show_downloads: true
theme: jekyll-theme-minimal
